# make sudo to enforce running on a real linux VM and not in a container on a macOS VM.
sudo: required
# do not use swift as language, since otherwise the build always runs on a macOS VM.
language: generic
dist: bionic # Ubuntu 18.04
osx_image: xcode11.2

compiler:
  - clang
  # currently it is not possible to compile with gcc
  # - gcc

os:
  - linux
  - osx

env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=4.1
  - SWIFT_VERSION=5.0
  - SWIFT_VERSION=5.1

before_install:
  - uname -a
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install clang-3.6
    fi

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - swift --version

script:
  - swift build
  - swift test
  - |
    # lint on osx only (no need to do this on every platform)
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swiftlint --strict
    fi
